# Fails: privileged container is not allowed
---
apiVersion: v1
kind: Pod
metadata:
  name: privileged-container
  labels:
    app: test
    env: dev
    owner: pedro
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: true
        readOnlyRootFilesystem: true
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
